spring.application.name: greatreads-data-loader

datadump.location:
  authors: G:/VS Code/test-authors.txt
  works: G:/VS Code/test-works.txt


spring:
  data:
    cassandra:
      keyspace-name: main
      username: <client id>
      password: <client secret>
      schema-action: create-if-not-exists
      request:
        timeout: 10s
      connection:
        connect-timeout: 10s
        init-query-timeout: 10s


datastax.astra:
    secure-connect-bundle: secure-connect.zip

astra.db:
    id: <db id>
    region: asia-south1
    keyspace: main
    application.token: <token>